server:
  port: 8081

spring:
  application:
    name: doctor-service.yml
  datasource:
    url: jdbc:mysql://localhost:3306/appointmentdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
